# Generated by Django 4.2.9 on 2024-02-19 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tasktype', models.CharField(blank=True, choices=[('S', 'Seasonal'), ('A', 'Annual'), ('M', 'Maintenance')], help_text='Classify the event', max_length=2, null=True)),
                ('repeatevent', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], help_text='Select if the event repeats or not', max_length=2, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'order_with_respect_to': 'user',
            },
        ),
    ]
